# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eaf98ac90102f467ffc102d91b1a83d8bd9e558a7c8f9e9f9ceb7b6e7f1c817e69a24bed668ed779499bc16871f3718556e6df0a484ee04d4310ade1f3083589

test:
  secret_key_base: 3d37c41b38748120f18bcb83d6ee4be6be3358084cc236faf040a67a94714658974fb1a36d1d3783734700e6c58bc68e89eb802e538c69222d7d104145d5e3bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
